#!/usr/bin/env node
/*
 * animayte — replay test (Route 3 / "the plumbing").  node test/replay.test.mjs
 *
 * Locks the CONTRACT of tools/animayte-replay.mjs: a REAL session transcript → the exact ordered
 * hook stream the daemon would have seen. This is the unit half (transcript → event plan); the
 * tool's own `--selftest` is the wire half (plan → live daemon → SSE reactions) and we run it here
 * too, so one `node test/replay.test.mjs` covers both.
 *
 * WHY a SEPARATE suite (and not run.mjs): replay is a dev/repro tool, not the shipped daemon — but
 * its parser is the thing most likely to silently rot as Claude Code's transcript JSON evolves
 * (the same class of bug that let the /compact regression ship green). So we lock the parser against
 * VERBATIM real transcript shapes, with red-without-fix discipline:
 *   · a tool_result's is_error must survive into the PostToolUse tool_response (the snag path)
 *   · command machinery (<command-name>…, [Request interrupted…) must NOT become a UserPromptSubmit
 *   · Stop must anchor to the REAL stop_hook_summary markers (one per turn) when present, and fall
 *     back to a synthesized turn-boundary Stop when they're absent
 *   · a sidechain (sub-agent) turn is tagged but still planned (so sidechain handling is verifiable)
 *   · the truncation index is monotonic and never exceeds the source (the temp transcript is valid)
 */
import { buildPlan, userPromptText, toolResultsIn, fixtureLines, selfTest } from '../tools/animayte-replay.mjs';

let pass = 0, fail = 0; const fails = [];
const ok = (name, cond, extra) => { if (cond) pass++; else { fail++; fails.push('  ✗ ' + name + (extra ? '  → ' + extra : '')); } };
const j = (o) => JSON.stringify(o);

console.log('\n· replay — transcript → faithful event plan');

// ── 1) The embedded fixture: the canonical praise → tool → happy-turn → /compact arc ──────────────
{
  const plan = buildPlan(fixtureLines('s1'), 's1');
  const kinds = plan.steps.map((s) => s.kind);
  ok('fixture: session id is picked up from the records', plan.sessionId === 's1', plan.sessionId);
  ok('fixture: a prompt step exists', kinds.includes('prompt'));
  ok('fixture: a tool_use step exists', kinds.includes('tool_use'));
  ok('fixture: a stop step exists', kinds.includes('stop'));
  ok('fixture: a compact step exists', kinds.includes('compact'));

  const tu = plan.steps.find((s) => s.kind === 'tool_use');
  ok('fixture: tool_use carries the real tool name + input', tu && tu.tool_name === 'Bash' && tu.tool_input.command === 'npm test', tu && j(tu.tool_input));
  ok('fixture: tool_use is paired with its result', tu && tu.result && tu.result.tool_use_id === 'toolu_replay_1');
  ok('fixture: the (ok) result is NOT flagged as an error', tu && tu.result && tu.result.is_error === false);

  // truncation index sanity: monotonic, in-bounds
  let lastIdx = -1, monotonic = true, inBounds = true;
  for (const s of plan.steps) {
    if (s.lineIndex == null) continue;
    if (s.lineIndex < lastIdx) monotonic = false; lastIdx = s.lineIndex;
    if (s.lineIndex >= plan.records.length) inBounds = false;
  }
  ok('fixture: step lineIndex is monotonic (temp transcript only ever grows)', monotonic);
  ok('fixture: step lineIndex never exceeds the source (valid truncation)', inBounds);
}

// ── 2) is_error MUST survive into the PostToolUse path (red without the reshaping) ────────────────
{
  // a tool_result whose content is an ARRAY of text blocks AND is_error:true (the real Bash-fail shape)
  const o = { type: 'user', message: { content: [{ type: 'tool_result', tool_use_id: 'tid', is_error: true, content: [{ type: 'text', text: 'build failed' }] }] } };
  const [tr] = toolResultsIn(o);
  ok('tool_result: array-content error preserves is_error', tr && tr.is_error === true);
  ok('tool_result: error reshaped so daemon isErrorResponse() (r.is_error===true) fires', tr && tr.response && tr.response.is_error === true, tr && j(tr.response));

  // a non-error string result stays a plain string (no false snag)
  const o2 = { type: 'user', message: { content: [{ type: 'tool_result', tool_use_id: 't2', is_error: false, content: 'all good' }] } };
  const [tr2] = toolResultsIn(o2);
  ok('tool_result: ok string result stays a string (no false error flag)', typeof tr2.response === 'string' && tr2.response === 'all good', j(tr2.response));
}

// ── 3) Command machinery must NOT be replayed as a user prompt ────────────────────────────────────
{
  const noise = [
    '<command-name>/compact</command-name>',
    '<local-command-stdout>Compacted</local-command-stdout>',
    '[Request interrupted by user]',
    'Caveat: The messages below were generated by the user while running a command.',
    'This session is being continued from a previous conversation that ran out of context.',
  ];
  const lines = noise.map((t) => j({ type: 'user', sessionId: 's', message: { role: 'user', content: t } }))
    .concat([j({ type: 'user', sessionId: 's', message: { role: 'user', content: 'please fix the bug, the build mentions <command-name> in its log' } })]);
  const plan = buildPlan(lines, 's');
  const realPrompts = plan.steps.filter((s) => s.kind === 'prompt');
  const noisePrompts = plan.steps.filter((s) => s.kind === 'prompt_noise');
  ok('noise: all 5 machinery records are classified as prompt_noise (skipped)', noisePrompts.length === 5, 'got ' + noisePrompts.length);
  ok('noise: a genuine prompt that MENTIONS <command-name> is still a real prompt', realPrompts.length === 1, 'got ' + realPrompts.length);

  // also exercise userPromptText directly: a tool_result envelope is not a prompt
  ok('userPromptText: a tool_result envelope returns null', userPromptText({ type: 'user', message: { content: [{ type: 'tool_result', tool_use_id: 'x', content: 'out' }] } }) === null);
  ok('userPromptText: an image meta note returns null', userPromptText({ type: 'user', isMeta: true, message: { content: '[Image: 100x100]' } }) === null);
}

// ── 4) Stop anchoring: REAL stop_hook_summary markers vs the synthesized fallback ─────────────────
{
  // WITH markers: two turns, each ending in a stop_hook_summary → exactly two Stop steps
  const withMarkers = [
    j({ type: 'user', sessionId: 's', message: { content: 'do a thing' } }),
    j({ type: 'assistant', sessionId: 's', message: { role: 'assistant', content: [{ type: 'tool_use', id: 'a1', name: 'Read', input: {} }], usage: { input_tokens: 10 } } }),
    j({ type: 'user', sessionId: 's', message: { content: [{ type: 'tool_result', tool_use_id: 'a1', is_error: false, content: 'ok' }] } }),
    j({ type: 'assistant', sessionId: 's', message: { role: 'assistant', content: [{ type: 'text', text: 'done one' }], usage: { input_tokens: 20 } } }),
    j({ type: 'system', subtype: 'stop_hook_summary', sessionId: 's' }),
    j({ type: 'assistant', sessionId: 's', message: { role: 'assistant', content: [{ type: 'text', text: 'and two' }], usage: { input_tokens: 30 } } }),
    j({ type: 'system', subtype: 'stop_hook_summary', sessionId: 's' }),
  ];
  const pm = buildPlan(withMarkers, 's');
  ok('stop(real): realStops flag is set when stop_hook_summary present', pm.realStops === true);
  ok('stop(real): exactly one Stop per real marker (2)', pm.steps.filter((s) => s.kind === 'stop').length === 2, 'got ' + pm.steps.filter((s) => s.kind === 'stop').length);

  // WITHOUT markers: the SAME content minus the markers → synthesized Stops at turn boundaries.
  // Turn boundary = an assistant text turn whose next record is NOT an assistant/tool_result. The
  // mid-turn assistant (the Read tool_use, followed by its tool_result) must NOT produce a Stop.
  const noMarkers = withMarkers.filter((l) => !l.includes('stop_hook_summary'));
  const pn = buildPlan(noMarkers, 's');
  ok('stop(synth): realStops flag is false without markers', pn.realStops === false);
  const synthStops = pn.steps.filter((s) => s.kind === 'stop');
  ok('stop(synth): a Stop is synthesized at the final turn boundary', synthStops.length >= 1, 'got ' + synthStops.length);
  // the tool_use turn (mid-turn, followed by a tool_result) must not be a stop point
  const stopLineIdxs = synthStops.map((s) => s.lineIndex);
  ok('stop(synth): the mid-turn tool_use line is NOT a Stop point', !stopLineIdxs.includes(1), 'stops at ' + j(stopLineIdxs));
}

// ── 5) Sub-agent (Agent/Task) → addBird is balanced by a SubagentStop on the tool result ─────────
{
  const lines = [
    j({ type: 'assistant', sessionId: 's', message: { role: 'assistant', content: [{ type: 'tool_use', id: 'g1', name: 'Agent', input: { description: 'research' } }], usage: { input_tokens: 5 } } }),
    j({ type: 'user', sessionId: 's', message: { content: [{ type: 'tool_result', tool_use_id: 'g1', is_error: false, content: 'found it' }] } }),
  ];
  const plan = buildPlan(lines, 's');
  const tu = plan.steps.find((s) => s.kind === 'tool_use');
  ok('subagent: an Agent tool_use is flagged isTask', tu && tu.isTask === true);
  ok('subagent: a SubagentStop step follows the Agent result (bird removed)', plan.steps.some((s) => s.kind === 'subagent_stop'));

  // a cut-off sub-agent (no result) leaves the bird orbiting (faithful to a truncated session)
  const cut = [j({ type: 'assistant', sessionId: 's', message: { role: 'assistant', content: [{ type: 'tool_use', id: 'g2', name: 'Agent', input: {} }] } })];
  const planCut = buildPlan(cut, 's');
  ok('subagent: a cut-off Agent (no result) emits NO SubagentStop', !planCut.steps.some((s) => s.kind === 'subagent_stop'));
}

// ── 6) Sidechain turns are tagged but still planned (sidechain handling stays verifiable) ─────────
{
  const lines = [
    j({ type: 'assistant', isSidechain: true, sessionId: 's', message: { role: 'assistant', content: [{ type: 'tool_use', id: 'sc1', name: 'Bash', input: { command: 'ls' } }], usage: { input_tokens: 5 } } }),
    j({ type: 'user', isSidechain: true, sessionId: 's', message: { content: [{ type: 'tool_result', tool_use_id: 'sc1', is_error: false, content: 'a b c' }] } }),
  ];
  const plan = buildPlan(lines, 's');
  const tu = plan.steps.find((s) => s.kind === 'tool_use');
  ok('sidechain: a sidechain tool_use is still planned and tagged', tu && tu.sidechain === true);
}

// ── 7) The live wire path: run the tool's embedded self-test (ephemeral daemon + SSE asserts) ─────
const liveOk = await selfTest();
ok('LIVE: tool --selftest passes (plan → daemon → SSE reactions)', liveOk === true);

const total = pass + fail;
console.log(`\n${fail === 0 ? '✅' : '❌'}  ${pass}/${total} replay checks passed` + (fail ? ':' : ''));
if (fail) { console.log(fails.join('\n')); process.exit(1); }
console.log('');
